site:
  title: Documentation
  url: http:localhost:5000
  start_page: hazelcast:ROOT:what-is-hazelcast.adoc
  robots: disallow
  keys:
    docsearch_id: 'QK2EAH8GB0'
    docsearch_api: 'ef7bd9485eafbd75d6e8425949eda1f5'
    docsearch_index: 'prod_hazelcast_docs'
urls:
  html_extension_style: drop    
content:
  sources: 
  - url: .
    branches: HEAD
    start_path: docs
  - url: https://github.com/hazelcast/cloud-docs
    branches: [main]
    start_path: docs
ui: 
  bundle:
    url: ../hazelcast-docs-ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    # Download images from kroki at build time (does not work for inline images)
    kroki-fetch-diagram: true
    # Inlude next and previous links on each page
    page-pagination: true@
    idprefix: ''
    # Separate anchor link names by dashes
    idseparator: '-'
    # Variables used in the docs
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    hazelcast-cloud: Cloud
    ucn: User Code Namespaces
    ucd: User Code Deployment
  extensions:
    - ./docs-tabs-library/tabs-block.js
    - asciidoctor-kroki
