# uncomment any of the sections to overwrite the global antora-playbook.yml

site:
#  title: Documentation
  url: https://hardcore-allen-f5257d.netlify.app/
  start_page: 6.0-snapshot@hazelcast:ROOT:what-is-hazelcast.adoc
  robots: disallow
#  keys:
#    docsearch_id: 'QK2EAH8GB0'
#    docsearch_api: 'ef7bd9485eafbd75d6e8425949eda1f5'
#    docsearch_index: 'prod_hazelcast_docs'
#    ai_search_id: '6b326171-dd1e-40c6-a948-1f9bb6c0ed52'
#content:
#  sources:
#  - url: .
#    branches: HEAD
#    start_path: docs
#  - url: https://github.com/hazelcast/hazelcast-mono
#    branches: [master]
#    start_path: docs/rest
#  - url: https://github.com/hazelcast/hazelcast-code-samples
#    branches: [test/docs]
#    start_path: docs
#ui:
#  bundle:
#    url: https://github.com/hazelcast/hazelcast-docs-ui/releases/latest/download/ui-bundle.zip #../hazelcast-docs-ui/build/ui-bundle.zip
#    snapshot: true
#asciidoc:
#  extensions:
#    - ./node_modules/hazelcast-docs-tools/antora-macro/tabs-block.js
#    - asciidoctor-kroki
#    - ./node_modules/hazelcast-docs-tools/antora-macro/swagger-ui-block-macro.js
