site:
  title: Documentation
  url: http:localhost:5000
content:
  sources: 
  - url: .
    branches: HEAD
    start_path: docs
  - url: https://github.com/hazelcast/imdg-docs
    branches: [master, v/*]
    start_path: docs
  - url: https://github.com/hazelcast/imdg-docs
    branches: [archived-versions]
    start_paths: docs/*
  - url: https://github.com/hazelcast/management-center-docs
    branches: [main, v/*]
    start_path: docs
  - url: https://github.com/hazelcast/management-center-docs
    branches: [archived-versions]
    start_paths: docs/*
  - url: https://github.com/hazelcast/cloud-docs
    branches: [main]
    start_path: docs
ui: 
  bundle:
    url: https://github.com/hazelcast/hazelcast-docs-ui/releases/download/v2.1/ui-bundle.zip #../hazelcast-docs-ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    # Download images from kroki at build time (does not work for inline images)
    kroki-fetch-diagram: true
    # Inlude next and previous links on each page
    page-pagination: true
    idprefix: ''
    # Separate anchor link names by dashes
    idseparator: '-'
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    distribution-link-windows: https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/5.0-SNAPSHOT/hazelcast-distribution-5.0-20210504.083718-133.zip
    distribution-link-mac-linux: https://oss.sonatype.org/content/repositories/snapshots/com/hazelcast/hazelcast-distribution/5.0-SNAPSHOT/hazelcast-distribution-5.0-20210504.083718-133.tar.gz
  extensions:
    - ./docs-tabs-library/tabs-block.js
    - asciidoctor-kroki
