name: Dispatch docs deployment

on:
  workflow_call:
    secrets:
      netlify_build_hook_id:
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
        #   https://docs.netlify.com/configure-builds/build-hooks/
      - run: curl -d {} https://api.netlify.com/build_hooks/${{ secrets.netlify_build_hook_id }}
